---
# Run on OS X
language: objective-c

before_install:
  - brew update

install:
  - sudo pip install ansible --quiet
    # This usually times out: http://docs.travis-ci.com/user/build-timeouts/
  - travis_wait brew install php55

script:
  - bash install.sh --skip-short-stack
  - ansible-playbook ~/.short-stack/stack.yml -i ~/.short-stack/inventory
