---
# Run on OS X
language: objective-c

before_install:
  - brew update

install:
  - sudo pip install ansible --quiet

script:
  - bash install.sh --skip-short-stack
  - ansible-playbook ~/.short-stack/stack.yml -i ~/.short-stack/inventory
