kb_key: "com.apple.keyboard.modifiermapping"
kb_map_dest: "HIDKeyboardModifierMappingDst"
kb_map_src: "HIDKeyboardModifierMappingSrc"

ss_osx_finder_defaults:
  # expand the save panel by default
  - { domain: NSGlobalDomain, key: NSNavPanelExpandedStateForSaveMode, type: boolean, value: true, state: present }
  # second expand save panel
  - { domain: NSGlobalDomain, key: NSNavPanelExpandedStateForSaveMode2, type: boolean, value: true, state: present }
  # disable the quarantine window prompt when install apps.
  - { domain: com.apple.LaunchServices, key: LSQuarantine, type: boolean, value: false, state: present }
  # double click title bars to minimize
  - { domain: NSGlobalDomain, key: AppleMiniaturizeOnDoubleClick, type: boolean, value: false, state: present }

  - { domain: NSGlobalDomain, key: AppleMiniaturizeOnDoubleClick, type: boolean, value: false, state: present }
  # disable window animations
  - { domain: NSGlobalDomain, key: NSAutomaticWindowAnimationsEnabled, type: boolean, value: false, state: present }
  # add finder QuitMenuItem
  - { domain: com.apple.finder, key: QuitMenuItem, type: boolean, value: true, state: present }
  # show status bar in finder
  - { domain: com.apple.finder, key: ShowStatusBar, type: boolean, value: true, state: present }
  # set airdrop over ethernet and unsopported macs
  - { domain: com.apple.NetworkBrowser, key: BrowseAllInterfaces, type: boolean, value: true, state: present }
  # show all extensions
  - { domain: com.apple.finder, key: AppleShowAllExtensions, type: boolean, value: true, state: present }
  # disable extension change warning
  - { domain: com.apple.finder, key: AppleShowAllExtensions, type: boolean, value: true, state: present }
  # tap with two fingers to right click
  - { domain: com.apple.driver.AppleBluetoothMultitouch.trackpad, key: TrackpadRightClick, type: boolean, value: true, state: present }
  # disable press-and-hold for keys in favor of key repeat
  - { domain: NSGlobalDomain, key: ApplePressAndHoldEnabled, type: boolean, value: false, state: present }
  # disable webkit homepage on sfari canary builds
  - { domain: org.webkit.nightly.WebKit, key: StartPageDisabled, type: boolean, value: true, state: present }
  # Enable the dev menu and web inspector in safari
  - { domain: com.apple.Safari, key: IncludeDevelopMenu, type: boolean, value: true, state: present }
  - { domain: com.apple.Safari, key: WebKitDeveloperExtrasEnabledPreferenceKey, type: boolean, value: true, state: present }
  - { domain: com.apple.Safari, key: com.apple.Safari.ContentPageGroupIdentifier.WebKit2DeveloperExtrasEnabled, type: boolean, value: true, state: present }
  - { domain: NSGlobalDomain, key: WebKitDeveloperExtras, type: boolean, value: true, state: present }
  # show icons for hard drives on desktop
  - { domain: com.apple.finder, key: ShowExternalHardDrivesOnDesktop, type: boolean, value: true, state: present }
  # show icons for servers on desktop
  - { domain: com.apple.finder, key: ShowMountedServersOnDesktop, type: boolean, value: true, state: present }
  # show icons for removable media on dekstop
  - { domain: com.apple.finder, key: ShowRemovableMediaOnDesktop, type: boolean, value: true, state: present }

ss_osx_dock_defaults:
  # autohide dock
  - { domain: com.apple.dock, key: autohide, type: boolean, value: true, state: present }
  # dim apps that have been hidden
  - { domain: com.apple.dock, key: showhidden, type: boolean, value: true, state: present }

