---
- homebrew: name=tmux state=latest

- file: path={{ vimrc_d }} state=directory
  when: "'vim' in role_names"

- copy: src=tmux.bundle dest={{ vimrc_d }}/tmux.bundle
  when: "'vim' in role_names"
  notify: vim bundle install

- name: create tmux conf.d dir
  file: path={{ vimrc_d }} state=directory

- copy: src=tmux.conf dest=~/.tmux.conf
- file: path={{ tmux_d }} state=directory

- name: add temporary folder to store fonts
  file: path=/tmp state=directory

- name: add patched powerline fonts
  git: repo=https://github.com/powerline/fonts.git dest=/tmp/fonts

- name: run powerline fonts installer
  shell: /tmp/fonts/install.sh
  register: font_installer_echo

- debug: msg="{{ font_installer_echo.stdout }}"

- name: cleanup temporary folder
  file: path=/tmp state=absent
