---
- name: install/update tmux
  homebrew: name=tmux state=latest

- name: add tmux plugins to vim
  copy: src=tmux.bundle dest={{ vimrc_d }}/tmux.bundle
  notify: vim bundle install

- name: copy .tmux.conf into ~
  copy: src=tmux.conf dest=~/.tmux.conf

- name: add tmux configuration to zsh
  copy: src=tmux.zsh dest={{ zshrc_d }}

- name: ensure ~/Library/Fonts directory exists
  file: path=~/Library/Fonts state=directory

- name: ensure monaco powerline patched font
  copy: src=monaco_for_powerline.otf dest='~/Library/Fonts/Monaco for Powerline.otf' force=no

- name: add tmux theme.conf
  copy: src=theme.conf dest=~/.tmux.d/theme.conf

- name: tap caskroom/fonts
  homebrew_tap: tap=caskroom/fonts state=present

- name: install/update powerline fonts
  homebrew_cask: name={{ item }} state=present
  with_items:
    - font-anonymous-pro-for-powerline
    - font-dejavu-sans-mono-for-powerline
    - font-droid-sans-mono-for-powerline
    - font-fira-mono-for-powerline
    - font-inconsolata-dz-for-powerline
    - font-inconsolata-for-powerline
    - font-inconsolata-g-for-powerline
    - font-liberation-mono-for-powerline
    - font-meslo-lg-for-powerline
    - font-sauce-code-powerline
    - font-source-code-pro-for-powerline
    - font-ubuntu-mono-powerline
