---
- name: install/update tmux
  homebrew: name=tmux state=latest

  name: ensure ~/.tmux.conf exists
- file: path=~/.tmux.conf state=touch

  name: add common.tmux to .tmux.conf
- lineinfile:
  args:
    dest: ~/.tmux.conf
    line: source {{ stack_d }}/common.tmux

- name: add tmux plugins to vim
  copy: src=tmux.bundle dest={{ stack_d }}/tmux.bundle
  notify: vim bundle install

- name: add tmux configuration to zsh
  copy: src=tmux.zsh dest={{ stack_d }}

- name: ensure ~/Library/Fonts directory exists
  file: path=~/Library/Fonts state=directory

- name: tap caskroom/cask so that brew-cask can be installed
  homebrew_tap: tap=caskroom/cask state=present

- name: install/update brew cask
  homebrew: name=brew-cask state=latest

- name: tap caskroom/fonts
  homebrew_tap: tap=caskroom/fonts state=present

- name: ensure inconsolata-g exists
  homebrew_cask: name=font-inconsolata-g-for-powerline state=present
