---
#
# To get a list of all short-stack roles see:
# https://github.com/poetic?query=short-stack

# Recommended roles
- src: https://github.com/poetic/short-stack-command-line-tools
  name: command-line-tools

- src: https://github.com/poetic/short-stack-tmux
  name: tmux

- src: https://github.com/poetic/short-stack-vim
  name: vim
