---
# To get a list of all short-stack roles see:
# https://github.com/poetic?query=short-stack

- src: https://github.com/poetic/short-stack-command-line-tools
  name: command-line-tools

- src: https://github.com/poetic/short-stack-osx
  name: osx

- src: https://github.com/poetic/short-stack-tmux
  name: tmux

- src: https://github.com/poetic/short-stack-vim
  name: vim

- src: https://github.com/poetic/short-stack-zsh
  name: zsh
