---
- name: tap caskroom/cask so that we can install brew-cask
  homebrew_tap: tap=caskroom/cask state=present

- name: install brew-cask
  homebrew: name=brew-cask state=latest

- name: Get app names from homebrew cask apps
  shell: brew cask info {{ item }} | grep -o -E '(.*)\.app|(.*)\.pkg' | sed -e 's/^[ \t]*//'
  with_items:
    - "{{ apps }}"
  register: app_info

- name: register apps that need to be installed
  shell: test -d '/Applications/{{ item.stdout }}' && echo "0" || echo "{{ item.item }}"
  with_items:
    - "{{ app_info.results }}"
  register: apps_to_install

- name: install applications using homebrew cask
  homebrew_cask: name={{ item.item.item }} state=present
  with_items:
    - "{{ apps_to_install.results }}"
  when: item.stdout != "0"

- name: uninstall cask apps present in /Applications
  homebrew_cask: name={{ item.item.item }} state=absent
  with_items:
    - "{{ apps_to_install.results }}"
  when: item.stdout == "0"

- name: ensure heroku toolbelt
  homebrew: name=heroku-toolbelt state=present

- name: ensure heroku accounts plugin
  command: heroku plugins:install git://github.com/ddollar/heroku-accounts.git
