---
- homebrew: name=vim state=latest

- homebrew_tap: tap=neovim/neovim state=present
- homebrew: name=neovim state=head

- copy: src=.vimrc dest=~/.vimrc

- file: path=~/.vim/autoload state=directory
- name: install vim-plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: ~/.vim/autoload/plug.vim

- file: path={{ vimrc_d }} state=directory
- copy: src={{ item }} dest={{ vimrc_d }}
  with_items:
    - common.vimrc
    - common.bundle
    - colors.bundle
