---
- homebrew: name=vim state=latest
- copy: src=vimrc.bundles.fork dest=~/.vimrc.bundles.fork
- copy: src=vimrc.before.fork dest=~/.vimrc.before.fork
- copy: src=vimrc.fork dest=~/.vimrc.fork

- name: Installing spf13-vim, The Ultimate Vim Distribution (http://vim.spf13.com)
  shell: curl https://j.mp/spf13-vim3 -L -o - | sh
  args:
    creates: ~/.spf13-vim-3/.vimrc
  notify: vim bundle install

- git:
  args:
    repo: https://github.com/spf13/spf13-vim.git
    dest: ~/.spf13-vim-3

- file: path={{ vimrc_d }} state=directory
- copy: src="{{ item }}.bundle" dest={{ vimrc_d }}
  with_items:
    - common
    - javascript
    - ruby
  notify: vim bundle install
