---
- homebrew: name=vim state=latest
- copy: src=vimrc.bundles.fork dest=~/.vimrc.bundles.fork
- copy: src=vimrc.before.fork dest=~/.vimrc.before.fork
- copy: src=vimrc.fork dest=~/.vimrc.fork

- file: path={{ vimrc_d }} state=directory
- copy: src="{{ item }}.bundle" dest={{ vimrc_d }}
  with_items:
    - common
    - javascript
    - ruby
  notify: vim bundle install
