---
- homebrew: name=vim state=latest

- name: install spf13
  shell: curl https://j.mp/spf13-vim3 -L -o - | sh
  args:
    creates: ~/.spf13-vim-3/.vimrc
  notify: vim bundle install

- name: update spf13
  git:
  args:
    repo: https://github.com/spf13/spf13-vim.git
    dest: ~/.spf13-vim-3
  notify: vim bundle install

- name: add .fork shims for nice vimrc.d structure
  copy: src={{ item }} dest=~/.{{ item }}
  with_items:
    - vimrc.bundles.fork
    - vimrc.before.fork
    - vimrc.fork

- name: create vimrd.d directory
  file: path={{ vimrc_d }} state=directory

- name: add config to vimrc.d
  copy: src={{ item }} dest={{ vimrc_d }}
  with_items:
    - common.bundle
    - common.vimrc
    - javascript.bundle
    - javascript.vimrc.before
    - ruby.bundle
  notify: vim bundle install

- name: add custom vim config to zsh
  copy: src=vim.zsh dest={{ zsh_c }}
