---
# GlobalDomain type defaults
#
# A lot of these were taken from mitchty @
# https://github.com/mitchty/bootstrap/blob/master/osx-user.yml
# and others from multiple other places on the web.

## Caps Lock Map
- name: get internal usb keyboard vendor/product ids
  shell: >
    ioreg -n IOHIDKeyboard -r |
    grep -E 'VendorID"|ProductID' |
    awk '{print $4}' |
    paste -s -d'-\n' -
  register: kb_id

- name: read builtin keyboard map for caps lock setup
  shell: >
    defaults -currentHost read -g
    "{{ kb_key }}.{{ kb_id.stdout }}-0" |
    perl -pe 's/(\n|\s+|{|}|\(|\)|\=|\;)//g' |
    perl -pe 's/HIDKeyboardModifierMapping//g'
  register: current_layout
  failed_when: no

- name: ensure builtin keyboard maps caps lock to control
  shell: >
    defaults -currentHost write -g
    "{{ kb_key }}.{{ kb_id.stdout }}-0"
    -array "{HIDKeyboardModifierMappingDst=2;HIDKeyboardModifierMappingSrc=0;}"
  when: current_layout.stdout != "Dst2Src0"

- name: osx configuration
  osx_defaults: domain={{ item.domain }} key={{ item.key }} type={{ item.type }} value={{ item.value }} state={{ item.state }}
  notify: restart finder
  with_items: ss_osx_finder_defaults

- osx_defaults: domain={{ item.domain }} key={{ item.key }} type={{ item.type }} value={{ item.value }} state={{ item.state }}
  notify: restart dock
  with_items: ss_osx_dock_defaults

#
# Need a pull request to support number type for:
# https://github.com/hnakamur/ansible-role-osx-defaults/blob/master/library/osx_defaults
# in order to finish implementing the commented out settings below
#

- name: Remove the auto-hiding Dock delay
  shell: defaults write com.apple.dock autohide-delay -float 0

- name: set blazingly fast keyboard repeat rate
  command: defaults write NSGlobalDomain KeyRepeat -int 0

- name: set shorter Delay UNTIL key repeat
  command: defaults write NSGlobalDomain InitialKeyRepeat -int 9

- name: set software updates daily
  command: defaults write com.apple.SoftwareUpdate ScheduleFrequency -int 1

- name: disable sound when changing volume
  command: defaults write -g com.apple.sound.beep.feedback -integer 0

- name: set trackpad tap to click
  command: defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad Clicking -bool true

- name: show the ~/Library folder
  shell: chflags nohidden ~/Library

- name: check that iOS simulator exists
  shell: "[ -f /Applications/Xcode.app/Contents/Developer/Applications/iOS\ Simulator.app ] && echo '1' || echo '0'"
  register: iOS_simulator_found

- name: Add iOS Simulator to Launchpad
  shell: ln -sf '/Applications/Xcode.app/Contents/Developer/Applications/iOS Simulator.app' '/Applications/iOS Simulator.app'
  when: iOS_simulator_found == 1

- name: set up iterm2 default config
  copy: src=com.googlecode.iterm2.plist dest=~/Library/Preferences/com.googlecode.iterm2.plist
